/*******************************************************************************
 *  Copyright FUJITSU LIMITED 2016 
 *******************************************************************************/

package org.oscm.mocksts.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "MockWebService", targetNamespace = "http://ws.mocksts.oscm.org/")
@XmlSeeAlso({ ObjectFactory.class })
public interface MockWebService {

    /**
     * 
     * @param name
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws.mocksts.oscm.org/", className = "org.oscm.mocksts.ws.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.mocksts.oscm.org/", className = "org.oscm.mocksts.ws.HelloResponse")
    @Action(input = "http://ws.mocksts.oscm.org/MockWebService/helloRequest", output = "http://ws.mocksts.oscm.org/MockWebService/helloResponse")
    public String hello(
            @WebParam(name = "name", targetNamespace = "") String name);

}
