/*******************************************************************************
 *  Copyright FUJITSU LIMITED 2017
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 12:50:01 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:SAML:2.0:protocol", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = @javax.xml.bind.annotation.XmlNs(prefix = "samlp", namespaceURI = "urn:oasis:names:tc:SAML:2.0:protocol"))
package org.oscm.saml2.api.model.protocol;

