heat_template_version: 2013-05-23

description: This is a Heat Orchestration template used for the creation and provisioning of a stack in FUJITSU Enterprise Cloud Service K5.

parameters:
  ImageId:
    description: The id of the image to provision.
    type: string
    default: <please input your image id>
  flavor:
    type: string
    description: flavor
    default: P-1
  KeyName:
    description: The name of an already defined key pair in OpenStack, used for enabling SSH access to the web server.
    type: string
    default: <please input your keypair name>
  az:
    type: string
    description: availability zone
    default: jp-west-1a
  VmName:
    type: string
    description: name of vm
  AdminPassword:
    type: string
  PrivateNetworkId:
    type: string
    description: internal network uuid
    default: <please input your internal network uuid>
  SubnetId:
    type: string
    description: subnet on which the load balancer will be located
  PublicNetworkId:
    type: string
    description: UUID of a Neutron external network
  SecurityGroupName:
    type: string
    description: security group
    
resources:
  sys-vol:
    type: OS::Cinder::Volume
    properties:
      name: "sys-vol"
      size: 80
      availability_zone: { get_param: az }
      volume_type: "M1"
      image : { get_param: ImageId }
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: KeyName }
      image: { get_param: ImageId }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: instanceport }
      name: { get_param: VmName }
      metadata: {"admin_pass": { get_param: AdminPassword }}
      availability_zone: { get_param: az }
      block_device_mapping: [{"device_name": "/dev/vda","volume_size": "100", "delete_on_termination": True, "volume_id": {get_resource: sys-vol}}]
  instanceport:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: PrivateNetworkId }
      security_groups: { get_param: SecurityGroupName }
      fixed_ips:
        - subnet_id: { get_param: SubnetId }
  instancepublic:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: PublicNetworkId }
      port_id: { get_resource: instanceport }
outputs:
  KP_Out:
    description: Key pair name
    value: { get_attr: [server, networks] }
 