steps:
# create folder oscmaas-dockerbuild with git repo
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/servicecatalog/oscm-dockerbuild.git']

# build image for ant commands
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gc-ant', '.']
  dir:  'oscm-dockerbuild/gc-ant'

# load libraries form maven repo via ivy
- name: 'gc-ant'
  args: ['-f', 'build-oscmaas.xml', 'BUILD.LIB']
  dir:  'oscm-devruntime/javares'
  
# start compile BES components
- name: 'gc-ant'
  args: ['-f', 'build-oscmaas.xml', 'BUILD.BES']
  dir:  'oscm-devruntime/javares'
  
# start compile APP components
- name: 'gc-ant'
  args: ['-f', 'build-oscmaas.xml', 'BUILD.APP']
  dir:  'oscm-devruntime/javares'

# copy necessary files to docker folders
- name: 'ubuntu'
  args: ['bash', './prepare.sh', '..']
  dir:  'oscm-dockerbuild'

# build images
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'oscm-gf', '.']
  dir:  'oscm-dockerbuild/oscm-gf'
  id:   'gf-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/oscm/oscm-bes:$TAG_NAME', '.']
  dir:  'oscm-dockerbuild/oscm-bes'
  waitFor: ['gf-image']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/oscm/oscm-app:$TAG_NAME', '.']
  dir:  'oscm-dockerbuild/oscm-app'
  waitFor: ['gf-image']
 
timeout: '3600s'
images: ['eu.gcr.io/$PROJECT_ID/oscm/oscm-bes:$TAG_NAME', 'eu.gcr.io/$PROJECT_ID/oscm/oscm-app:$TAG_NAME']