ALTER TABLE "marketplace" ADD COLUMN "open" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "marketplacehistory" ADD COLUMN "open" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "marketplacetoorganization" ADD COLUMN "publishingaccess" VARCHAR(255) NOT NULL DEFAULT 'PUBLISHING_ACCESS_GRANTED';
ALTER TABLE "marketplacetoorganizationhistory" ADD COLUMN "publishingaccess" VARCHAR(255) NOT NULL DEFAULT 'PUBLISHING_ACCESS_GRANTED';
