/*******************************************************************************
 *  Copyright FUJITSU LIMITED 2016 
 *******************************************************************************/

package org.oscm.xsd.v1;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientSoapHandlerService", targetNamespace = "http://oscm.org/xsd", wsdlLocation = "http://localhost:8680/oscm-integration-ws-security-client/ClientSoapHandlerService?wsdl")
public class ClientSoapHandlerService_Service extends Service {

    private final static URL CLIENTSOAPHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTSOAPHANDLERSERVICE_EXCEPTION;
    private final static QName CLIENTSOAPHANDLERSERVICE_QNAME = new QName(
            "http://oscm.org/xsd", "ClientSoapHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(
                    "http://localhost:8680/oscm-integration-ws-security-client/ClientSoapHandlerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTSOAPHANDLERSERVICE_WSDL_LOCATION = url;
        CLIENTSOAPHANDLERSERVICE_EXCEPTION = e;
    }

    public ClientSoapHandlerService_Service() {
        super(__getWsdlLocation(), CLIENTSOAPHANDLERSERVICE_QNAME);
    }

    public ClientSoapHandlerService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTSOAPHANDLERSERVICE_QNAME, features);
    }

    public ClientSoapHandlerService_Service(URL wsdlLocation) {
        super(wsdlLocation, CLIENTSOAPHANDLERSERVICE_QNAME);
    }

    public ClientSoapHandlerService_Service(URL wsdlLocation,
            WebServiceFeature... features) {
        super(wsdlLocation, CLIENTSOAPHANDLERSERVICE_QNAME, features);
    }

    public ClientSoapHandlerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientSoapHandlerService_Service(URL wsdlLocation,
            QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns ClientSoapHandlerService
     */
    @WebEndpoint(name = "ClientSoapHandlerServiceImplPort")
    public ClientSoapHandlerService getClientSoapHandlerServiceImplPort() {
        return super.getPort(new QName("http://oscm.org/xsd",
                "ClientSoapHandlerServiceImplPort"),
                ClientSoapHandlerService.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns ClientSoapHandlerService
     */
    @WebEndpoint(name = "ClientSoapHandlerServiceImplPort")
    public ClientSoapHandlerService getClientSoapHandlerServiceImplPort(
            WebServiceFeature... features) {
        return super.getPort(new QName("http://oscm.org/xsd",
                "ClientSoapHandlerServiceImplPort"),
                ClientSoapHandlerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTSOAPHANDLERSERVICE_EXCEPTION != null) {
            throw CLIENTSOAPHANDLERSERVICE_EXCEPTION;
        }
        return CLIENTSOAPHANDLERSERVICE_WSDL_LOCATION;
    }

}
