/*******************************************************************************
 *  Copyright FUJITSU LIMITED 2017
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.05 at 01:29:11 PM CET 
//


package org.oscm.billingservice.business.model.billingresult;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Event.
 * 
 * <p>Java class for EventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SingleCost" type="{}CostsType" minOccurs="0"/>
 *         &lt;element name="SteppedPrices" type="{}SteppedPricesType" minOccurs="0"/>
 *         &lt;element name="NumberOfOccurrence" type="{}NumberOfOccurrenceType"/>
 *         &lt;element name="CostForEventType" type="{}NormalizedCostsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType", propOrder = {
    "description",
    "singleCost",
    "steppedPrices",
    "numberOfOccurrence",
    "costForEventType"
})
public class EventType {

    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "SingleCost")
    protected CostsType singleCost;
    @XmlElement(name = "SteppedPrices")
    protected SteppedPricesType steppedPrices;
    @XmlElement(name = "NumberOfOccurrence", required = true)
    protected NumberOfOccurrenceType numberOfOccurrence;
    @XmlElement(name = "CostForEventType", required = true)
    protected NormalizedCostsType costForEventType;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the singleCost property.
     * 
     * @return
     *     possible object is
     *     {@link CostsType }
     *     
     */
    public CostsType getSingleCost() {
        return singleCost;
    }

    /**
     * Sets the value of the singleCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link CostsType }
     *     
     */
    public void setSingleCost(CostsType value) {
        this.singleCost = value;
    }

    /**
     * Gets the value of the steppedPrices property.
     * 
     * @return
     *     possible object is
     *     {@link SteppedPricesType }
     *     
     */
    public SteppedPricesType getSteppedPrices() {
        return steppedPrices;
    }

    /**
     * Sets the value of the steppedPrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link SteppedPricesType }
     *     
     */
    public void setSteppedPrices(SteppedPricesType value) {
        this.steppedPrices = value;
    }

    /**
     * Gets the value of the numberOfOccurrence property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfOccurrenceType }
     *     
     */
    public NumberOfOccurrenceType getNumberOfOccurrence() {
        return numberOfOccurrence;
    }

    /**
     * Sets the value of the numberOfOccurrence property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfOccurrenceType }
     *     
     */
    public void setNumberOfOccurrence(NumberOfOccurrenceType value) {
        this.numberOfOccurrence = value;
    }

    /**
     * Gets the value of the costForEventType property.
     * 
     * @return
     *     possible object is
     *     {@link NormalizedCostsType }
     *     
     */
    public NormalizedCostsType getCostForEventType() {
        return costForEventType;
    }

    /**
     * Sets the value of the costForEventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NormalizedCostsType }
     *     
     */
    public void setCostForEventType(NormalizedCostsType value) {
        this.costForEventType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
