/*******************************************************************************
 *  Copyright FUJITSU LIMITED 2017
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.09 at 03:35:54 PM CEST 
//

package org.oscm.billingservice.business.model.billingresult;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the test.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Billingdata_QNAME = new QName("", "Billingdata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: test.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BillingdataType }
     * 
     */
    public BillingdataType createBillingdataType() {
        return new BillingdataType();
    }

    /**
     * Create an instance of {@link OverallCostsType }
     * 
     */
    public OverallCostsType createOverallCostsType() {
        return new OverallCostsType();
    }

    /**
     * Create an instance of {@link ParametersType }
     * 
     */
    public ParametersType createParametersType() {
        return new ParametersType();
    }

    /**
     * Create an instance of {@link NumberOfOccurrenceType }
     * 
     */
    public NumberOfOccurrenceType createNumberOfOccurrenceType() {
        return new NumberOfOccurrenceType();
    }

    /**
     * Create an instance of {@link PeriodType }
     * 
     */
    public PeriodType createPeriodType() {
        return new PeriodType();
    }

    /**
     * Create an instance of {@link UdaType }
     * 
     */
    public UdaType createUdaType() {
        return new UdaType();
    }

    /**
     * Create an instance of {@link ParameterValueType }
     * 
     */
    public ParameterValueType createParameterValueType() {
        return new ParameterValueType();
    }

    /**
     * Create an instance of {@link BillingDetailsType }
     * 
     */
    public BillingDetailsType createBillingDetailsType() {
        return new BillingDetailsType();
    }

    /**
     * Create an instance of {@link OneTimeFeeType }
     * 
     */
    public OneTimeFeeType createOneTimeFeeType() {
        return new OneTimeFeeType();
    }

    /**
     * Create an instance of {@link VATType }
     * 
     */
    public VATType createVATType() {
        return new VATType();
    }

    /**
     * Create an instance of {@link OrganizationalUnitType }
     * 
     */
    public OrganizationalUnitType createOrganizationalUnitType() {
        return new OrganizationalUnitType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link RoleCostsType }
     * 
     */
    public RoleCostsType createRoleCostsType() {
        return new RoleCostsType();
    }

    /**
     * Create an instance of {@link UserAssignmentCostsByUserType }
     * 
     */
    public UserAssignmentCostsByUserType createUserAssignmentCostsByUserType() {
        return new UserAssignmentCostsByUserType();
    }

    /**
     * Create an instance of {@link PriceModelsType }
     * 
     */
    public PriceModelsType createPriceModelsType() {
        return new PriceModelsType();
    }

    /**
     * Create an instance of {@link UserAssignmentCostsType }
     * 
     */
    public UserAssignmentCostsType createUserAssignmentCostsType() {
        return new UserAssignmentCostsType();
    }

    /**
     * Create an instance of {@link ParameterPeriodFeeType }
     * 
     */
    public ParameterPeriodFeeType createParameterPeriodFeeType() {
        return new ParameterPeriodFeeType();
    }

    /**
     * Create an instance of {@link GatheredEventsType }
     * 
     */
    public GatheredEventsType createGatheredEventsType() {
        return new GatheredEventsType();
    }

    /**
     * Create an instance of {@link RoleCostType }
     * 
     */
    public RoleCostType createRoleCostType() {
        return new RoleCostType();
    }

    /**
     * Create an instance of {@link SubscriptionType }
     * 
     */
    public SubscriptionType createSubscriptionType() {
        return new SubscriptionType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link SteppedPriceType }
     * 
     */
    public SteppedPriceType createSteppedPriceType() {
        return new SteppedPriceType();
    }

    /**
     * Create an instance of {@link ParameterOptionsType }
     * 
     */
    public ParameterOptionsType createParameterOptionsType() {
        return new ParameterOptionsType();
    }

    /**
     * Create an instance of {@link ParameterOptionType }
     * 
     */
    public ParameterOptionType createParameterOptionType() {
        return new ParameterOptionType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link NormalizedCostsType }
     * 
     */
    public NormalizedCostsType createNormalizedCostsType() {
        return new NormalizedCostsType();
    }

    /**
     * Create an instance of {@link UdasType }
     * 
     */
    public UdasType createUdasType() {
        return new UdasType();
    }

    /**
     * Create an instance of {@link OrganizationDetailsType }
     * 
     */
    public OrganizationDetailsType createOrganizationDetailsType() {
        return new OrganizationDetailsType();
    }

    /**
     * Create an instance of {@link DetailedCostsType }
     * 
     */
    public DetailedCostsType createDetailedCostsType() {
        return new DetailedCostsType();
    }

    /**
     * Create an instance of {@link PeriodFeeType }
     * 
     */
    public PeriodFeeType createPeriodFeeType() {
        return new PeriodFeeType();
    }

    /**
     * Create an instance of {@link PriceModelType }
     * 
     */
    public PriceModelType createPriceModelType() {
        return new PriceModelType();
    }

    /**
     * Create an instance of {@link SubscriptionsType }
     * 
     */
    public SubscriptionsType createSubscriptionsType() {
        return new SubscriptionsType();
    }

    /**
     * Create an instance of {@link ParameterUserAssignmentCostsType }
     * 
     */
    public ParameterUserAssignmentCostsType createParameterUserAssignmentCostsType() {
        return new ParameterUserAssignmentCostsType();
    }

    /**
     * Create an instance of {@link CostsType }
     * 
     */
    public CostsType createCostsType() {
        return new CostsType();
    }

    /**
     * Create an instance of {@link ParametersUserAssignmentCostsType }
     * 
     */
    public ParametersUserAssignmentCostsType createParametersUserAssignmentCostsType() {
        return new ParametersUserAssignmentCostsType();
    }

    /**
     * Create an instance of {@link SteppedPricesType }
     * 
     */
    public SteppedPricesType createSteppedPricesType() {
        return new SteppedPricesType();
    }

    /**
     * Create an instance of {@link DiscountType }
     * 
     */
    public DiscountType createDiscountType() {
        return new DiscountType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillingdataType }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Billingdata")
    public JAXBElement<BillingdataType> createBillingdata(BillingdataType value) {
        return new JAXBElement<BillingdataType>(_Billingdata_QNAME,
                BillingdataType.class, null, value);
    }

}
