/*******************************************************************************
 *  Copyright FUJITSU LIMITED 2017
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.05 at 01:29:11 PM CET 
//


package org.oscm.billingservice.business.model.billingresult;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Parameter.
 * 
 * <p>Java class for ParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParameterUsagePeriod" type="{}PeriodType" minOccurs="0"/>
 *         &lt;element name="ParameterValue" type="{}ParameterValueType"/>
 *         &lt;element name="Options" type="{}ParameterOptionsType" minOccurs="0"/>
 *         &lt;element name="PeriodFee" type="{}ParameterPeriodFeeType" minOccurs="0"/>
 *         &lt;element name="UserAssignmentCosts" type="{}ParameterUserAssignmentCostsType" minOccurs="0"/>
 *         &lt;element name="ParameterCosts" type="{}NormalizedCostsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterType", propOrder = {
    "parameterUsagePeriod",
    "parameterValue",
    "options",
    "periodFee",
    "userAssignmentCosts",
    "parameterCosts"
})
public class ParameterType {

    @XmlElement(name = "ParameterUsagePeriod")
    protected PeriodType parameterUsagePeriod;
    @XmlElement(name = "ParameterValue", required = true)
    protected ParameterValueType parameterValue;
    @XmlElement(name = "Options")
    protected ParameterOptionsType options;
    @XmlElement(name = "PeriodFee")
    protected ParameterPeriodFeeType periodFee;
    @XmlElement(name = "UserAssignmentCosts")
    protected ParameterUserAssignmentCostsType userAssignmentCosts;
    @XmlElement(name = "ParameterCosts", required = true)
    protected NormalizedCostsType parameterCosts;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the parameterUsagePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodType }
     *     
     */
    public PeriodType getParameterUsagePeriod() {
        return parameterUsagePeriod;
    }

    /**
     * Sets the value of the parameterUsagePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodType }
     *     
     */
    public void setParameterUsagePeriod(PeriodType value) {
        this.parameterUsagePeriod = value;
    }

    /**
     * Gets the value of the parameterValue property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterValueType }
     *     
     */
    public ParameterValueType getParameterValue() {
        return parameterValue;
    }

    /**
     * Sets the value of the parameterValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterValueType }
     *     
     */
    public void setParameterValue(ParameterValueType value) {
        this.parameterValue = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterOptionsType }
     *     
     */
    public ParameterOptionsType getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterOptionsType }
     *     
     */
    public void setOptions(ParameterOptionsType value) {
        this.options = value;
    }

    /**
     * Gets the value of the periodFee property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterPeriodFeeType }
     *     
     */
    public ParameterPeriodFeeType getPeriodFee() {
        return periodFee;
    }

    /**
     * Sets the value of the periodFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterPeriodFeeType }
     *     
     */
    public void setPeriodFee(ParameterPeriodFeeType value) {
        this.periodFee = value;
    }

    /**
     * Gets the value of the userAssignmentCosts property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterUserAssignmentCostsType }
     *     
     */
    public ParameterUserAssignmentCostsType getUserAssignmentCosts() {
        return userAssignmentCosts;
    }

    /**
     * Sets the value of the userAssignmentCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterUserAssignmentCostsType }
     *     
     */
    public void setUserAssignmentCosts(ParameterUserAssignmentCostsType value) {
        this.userAssignmentCosts = value;
    }

    /**
     * Gets the value of the parameterCosts property.
     * 
     * @return
     *     possible object is
     *     {@link NormalizedCostsType }
     *     
     */
    public NormalizedCostsType getParameterCosts() {
        return parameterCosts;
    }

    /**
     * Sets the value of the parameterCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link NormalizedCostsType }
     *     
     */
    public void setParameterCosts(NormalizedCostsType value) {
        this.parameterCosts = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
