/*******************************************************************************
 *  Copyright FUJITSU LIMITED 2017
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.05 at 01:29:11 PM CET 
//

package org.oscm.billingservice.business.model.billingresult;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.oscm.billingservice.business.BigDecimalAdapter;

/**
 * Costs for using the parameter.
 * 
 * <p>
 * Java class for ParameterPeriodFeeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterPeriodFeeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SteppedPrices" type="{}SteppedPricesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="basePeriod" use="required" type="{}basePeriodType" />
 *       &lt;attribute name="basePrice" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="factor" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="price" use="required" type="{}NormalizedCosts" />
 *       &lt;attribute name="valueFactor" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterPeriodFeeType", propOrder = { "steppedPrices" })
public class ParameterPeriodFeeType {

    @XmlElement(name = "SteppedPrices")
    protected SteppedPricesType steppedPrices;

    @XmlAttribute(required = true)
    protected BasePeriodType basePeriod;

    @XmlAttribute
    @XmlJavaTypeAdapter(BigDecimalAdapter.class)
    protected BigDecimal basePrice;

    @XmlAttribute(required = true)
    protected BigDecimal factor;

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(BigDecimalAdapter.class)
    protected BigDecimal price;

    @XmlAttribute(required = true)
    protected float valueFactor;

    /**
     * Gets the value of the steppedPrices property.
     * 
     * @return possible object is {@link SteppedPricesType }
     * 
     */
    public SteppedPricesType getSteppedPrices() {
        return steppedPrices;
    }

    /**
     * Sets the value of the steppedPrices property.
     * 
     * @param value
     *            allowed object is {@link SteppedPricesType }
     * 
     */
    public void setSteppedPrices(SteppedPricesType value) {
        this.steppedPrices = value;
    }

    /**
     * Gets the value of the basePeriod property.
     * 
     * @return possible object is {@link BasePeriodType }
     * 
     */
    public BasePeriodType getBasePeriod() {
        return basePeriod;
    }

    /**
     * Sets the value of the basePeriod property.
     * 
     * @param value
     *            allowed object is {@link BasePeriodType }
     * 
     */
    public void setBasePeriod(BasePeriodType value) {
        this.basePeriod = value;
    }

    /**
     * Gets the value of the basePrice property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * Sets the value of the basePrice property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setBasePrice(BigDecimal value) {
        this.basePrice = value;
    }

    /**
     * Gets the value of the factor property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getFactor() {
        return factor;
    }

    /**
     * Sets the value of the factor property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setFactor(BigDecimal value) {
        this.factor = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the valueFactor property.
     * 
     */
    public float getValueFactor() {
        return valueFactor;
    }

    /**
     * Sets the value of the valueFactor property.
     * 
     */
    public void setValueFactor(float value) {
        this.valueFactor = value;
    }

}
