/*******************************************************************************
 *  Copyright FUJITSU LIMITED 2017
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.05 at 01:29:11 PM CET 
//

package org.oscm.billingservice.business.model.billingresult;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.oscm.billingservice.business.BigDecimalAdapter;

/**
 * Stepped price element.
 * 
 * <p>
 * Java class for SteppedPriceType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SteppedPriceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="additionalPrice" use="required" type="{}NormalizedCosts" />
 *       &lt;attribute name="basePrice" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="freeAmount" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="limit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stepAmount" type="{}NormalizedCosts" />
 *       &lt;attribute name="stepEntityCount" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SteppedPriceType")
public class SteppedPriceType {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(BigDecimalAdapter.class)
    protected BigDecimal additionalPrice;

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(BigDecimalAdapter.class)
    protected BigDecimal basePrice;

    @XmlAttribute(required = true)
    protected long freeAmount;

    @XmlAttribute(required = true)
    protected String limit;

    @XmlAttribute
    @XmlJavaTypeAdapter(BigDecimalAdapter.class)
    protected BigDecimal stepAmount;

    @XmlAttribute
    protected BigDecimal stepEntityCount;

    /**
     * Gets the value of the additionalPrice property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getAdditionalPrice() {
        return additionalPrice;
    }

    /**
     * Sets the value of the additionalPrice property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setAdditionalPrice(BigDecimal value) {
        this.additionalPrice = value;
    }

    /**
     * Gets the value of the basePrice property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * Sets the value of the basePrice property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setBasePrice(BigDecimal value) {
        this.basePrice = value;
    }

    /**
     * Gets the value of the freeAmount property.
     * 
     */
    public long getFreeAmount() {
        return freeAmount;
    }

    /**
     * Sets the value of the freeAmount property.
     * 
     */
    public void setFreeAmount(long value) {
        this.freeAmount = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLimit(String value) {
        this.limit = value;
    }

    /**
     * Gets the value of the stepAmount property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getStepAmount() {
        return stepAmount;
    }

    /**
     * Sets the value of the stepAmount property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setStepAmount(BigDecimal value) {
        this.stepAmount = value;
    }

    /**
     * Gets the value of the stepEntityCount property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getStepEntityCount() {
        return stepEntityCount;
    }

    /**
     * Sets the value of the stepEntityCount property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setStepEntityCount(BigDecimal value) {
        this.stepEntityCount = value;
    }

}
