/*******************************************************************************
 *  Copyright FUJITSU LIMITED 2017
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.05 at 01:29:11 PM CET 
//

package org.oscm.billingservice.business.model.billingresult;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.oscm.billingservice.business.BigDecimalAdapter;

/**
 * Costs that occurred due to assignments of users to the subscription.
 * 
 * <p>
 * Java class for UserAssignmentCostsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="UserAssignmentCostsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserAssignmentCostsByUser" type="{}UserAssignmentCostsByUserType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RoleCosts" type="{}RoleCostsType" minOccurs="0"/>
 *         &lt;element name="SteppedPrices" type="{}SteppedPricesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="basePeriod" type="{}basePeriodType" />
 *       &lt;attribute name="basePrice" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="factor" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="numberOfUsersTotal" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="total" type="{}NormalizedCosts" />
 *       &lt;attribute name="price" type="{}NormalizedCosts" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserAssignmentCostsType", propOrder = {
        "userAssignmentCostsByUser", "roleCosts", "steppedPrices" })
public class UserAssignmentCostsType {

    @XmlElement(name = "UserAssignmentCostsByUser")
    protected List<UserAssignmentCostsByUserType> userAssignmentCostsByUser;

    @XmlElement(name = "RoleCosts")
    protected RoleCostsType roleCosts;

    @XmlElement(name = "SteppedPrices")
    protected SteppedPricesType steppedPrices;

    @XmlAttribute
    protected BasePeriodType basePeriod;

    @XmlAttribute
    @XmlJavaTypeAdapter(BigDecimalAdapter.class)
    protected BigDecimal basePrice;

    @XmlAttribute
    protected BigDecimal factor;

    @XmlAttribute
    protected Long numberOfUsersTotal;

    @XmlAttribute
    @XmlJavaTypeAdapter(BigDecimalAdapter.class)
    protected BigDecimal total;

    @XmlAttribute
    @XmlJavaTypeAdapter(BigDecimalAdapter.class)
    protected BigDecimal price;

    /**
     * Gets the value of the userAssignmentCostsByUser property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the userAssignmentCostsByUser property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getUserAssignmentCostsByUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserAssignmentCostsByUserType }
     * 
     * 
     */
    public List<UserAssignmentCostsByUserType> getUserAssignmentCostsByUser() {
        if (userAssignmentCostsByUser == null) {
            userAssignmentCostsByUser = new ArrayList<UserAssignmentCostsByUserType>();
        }
        return this.userAssignmentCostsByUser;
    }

    /**
     * Gets the value of the roleCosts property.
     * 
     * @return possible object is {@link RoleCostsType }
     * 
     */
    public RoleCostsType getRoleCosts() {
        return roleCosts;
    }

    /**
     * Sets the value of the roleCosts property.
     * 
     * @param value
     *            allowed object is {@link RoleCostsType }
     * 
     */
    public void setRoleCosts(RoleCostsType value) {
        this.roleCosts = value;
    }

    /**
     * Gets the value of the steppedPrices property.
     * 
     * @return possible object is {@link SteppedPricesType }
     * 
     */
    public SteppedPricesType getSteppedPrices() {
        return steppedPrices;
    }

    /**
     * Sets the value of the steppedPrices property.
     * 
     * @param value
     *            allowed object is {@link SteppedPricesType }
     * 
     */
    public void setSteppedPrices(SteppedPricesType value) {
        this.steppedPrices = value;
    }

    /**
     * Gets the value of the basePeriod property.
     * 
     * @return possible object is {@link BasePeriodType }
     * 
     */
    public BasePeriodType getBasePeriod() {
        return basePeriod;
    }

    /**
     * Sets the value of the basePeriod property.
     * 
     * @param value
     *            allowed object is {@link BasePeriodType }
     * 
     */
    public void setBasePeriod(BasePeriodType value) {
        this.basePeriod = value;
    }

    /**
     * Gets the value of the basePrice property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * Sets the value of the basePrice property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setBasePrice(BigDecimal value) {
        this.basePrice = value;
    }

    /**
     * Gets the value of the factor property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getFactor() {
        return factor;
    }

    /**
     * Sets the value of the factor property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setFactor(BigDecimal value) {
        this.factor = value;
    }

    /**
     * Gets the value of the numberOfUsersTotal property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getNumberOfUsersTotal() {
        return numberOfUsersTotal;
    }

    /**
     * Sets the value of the numberOfUsersTotal property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setNumberOfUsersTotal(Long value) {
        this.numberOfUsersTotal = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setTotal(BigDecimal value) {
        this.total = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *            allowed object is {@link BigDecimal }
     * 
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

}
